---
service: es-disclosure-sg
provider:
  name: aws
  deploymentBucket:
    name: com.serverless.${self:provider.region}.results.ons.deploys
  role: arn:aws:iam::${self:custom.accountId}:role/lambda_invoke_lambda
  vpc:
    securityGroupIds:
      - ${file(../json_outputs/security_groups_output.json):SecurityGroups.0.GroupId}
    subnetIds:
      - ${file(../json_outputs/subnets_output.json):Subnets.0.SubnetId}
      - ${file(../json_outputs/subnets_output.json):Subnets.1.SubnetId}
  runtime: python3.7
  region: eu-west-2
  package:
    individually: true
  memorySize: 1024
  timeout: 20
  tracing:
    lambda: true

custom:
  accounts: ${ssm:/aws/reference/secretsmanager/results-aws-accounts~true}
  accountId: ${self:custom.accounts.account-id}

functions:
  deploy-disclosure-wrangler:
    name: es-disclosure-wrangler
    handler: disclosure_wrangler.lambda_handler
    package:
      individually: true
      include:
        - disclosure_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:latest
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-common-functions:latest
    tags:
      app: results
    environment:
      checkpoint: 5
      bucket_name: results-s3-bucket
      in_file_name: aggregation_out.json
      incoming_message_group: agg-combiner
      method_name: es-disclosure-stage--method
      out_file_name: disclosure_out.json
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_message_group_id: disclosure-out
      sqs_queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo
      csv_file_name: output/final_output.csv
      reference: responder_id

  deploy-stage-1-method:
    name: es-disclosure-stage-1-method
    handler: stage1_method.lambda_handler
    package:
      individually: true
      include:
        - stage1_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:latest
    tags:
      app: results

  deploy-stage-2-method:
    name: es-disclosure-stage-2-method
    handler: stage2_method.lambda_handler
    package:
      individually: true
      include:
        - stage2_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:latest
    tags:
      app: results

  deploy-stage-3-method:
    name: es-disclosure-stage-3-method
    handler: stage3_method.lambda_handler
    package:
      include:
        - stage3_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:latest
    tags:
      app: results

  deploy-stage-4-method:
    name: es-disclosure-stage-4-method
    handler: stage4_method.lambda_handler
    package:
      individually: true
      include:
        - stage5_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:latest
    tags:
      app: results

  deploy-stage-5-method:
    name: es-disclosure-stage-5-method
    handler: stage5_method.lambda_handler
    package:
      individually: true
      include:
        - stage5_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:latest
    tags:
      app: results

plugins:
  - serverless-latest-layer-version